<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '6e3027ed3637000d14adee8b33803b57',
  'MAILER_DSN' => 'smtp://amcem@amcem-menuiserie:amcem2021@smtp.ionos.fr',
  'DATABASE_URL' => 'mysql://dbu1975605:amcem2021@localhost:3306/dbs5081867?serverVersion=5.7',
);
